//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectUASVisprog.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-2E3LG5H\\SQLEXPRESS01;Initial Catalog=ProjectVisualProgramming" +
            ";Integrated Security=True")]
        public string ProjectVisualProgrammingConnectionString {
            get {
                return ((string)(this["ProjectVisualProgrammingConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-2E3LG5H\\SQLEXPRESS01;Initial Catalog=ProjekVisprogNew;Integra" +
            "ted Security=True")]
        public string ProjekVisprogNewConnectionString {
            get {
                return ((string)(this["ProjekVisprogNewConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-2E3LG5H\\SQLEXPRESS01;Initial Catalog=TestingVisprog;Integrate" +
            "d Security=True")]
        public string TestingVisprogConnectionString {
            get {
                return ((string)(this["TestingVisprogConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-2E3LG5H\\SQLEXPRESS01;Initial Catalog=TestingVisprog2;Integrat" +
            "ed Security=True")]
        public string TestingVisprog2ConnectionString {
            get {
                return ((string)(this["TestingVisprog2ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-2E3LG5H\\SQLEXPRESS01;Initial Catalog=TestingVisprog3;Integrat" +
            "ed Security=True")]
        public string TestingVisprog3ConnectionString {
            get {
                return ((string)(this["TestingVisprog3ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-2E3LG5H\\SQLEXPRESS01;Initial Catalog=TestingVisprog5;Integrat" +
            "ed Security=True")]
        public string TestingVisprog5ConnectionString {
            get {
                return ((string)(this["TestingVisprog5ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-2E3LG5H\\SQLEXPRESS01;Initial Catalog=TestingVisprog6;Integrat" +
            "ed Security=True")]
        public string TestingVisprog6ConnectionString {
            get {
                return ((string)(this["TestingVisprog6ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-2E3LG5H\\SQLEXPRESS01;Initial Catalog=TestingVisprogFinal;Inte" +
            "grated Security=True")]
        public string TestingVisprogFinalConnectionString {
            get {
                return ((string)(this["TestingVisprogFinalConnectionString"]));
            }
        }
    }
}
